planner_server:
  ros__parameters:
    expected_planner_frequency: 2.0
    use_sim_time: true
    transform_tolerance: 2.0
    planner_plugins: ["GridBased"]
    GridBased:
     #plugin: "ttbot_planning::AStarPlanner"

     plugin: "ttbot_planning::AStarPlannerNew"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      transform_tolerance: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      footprint: "[ [0.5, 0.35], [0.5, -0.35], [-0.5, -0.35], [-0.5, 0.35] ]"
      resolution: 0.05
      track_unknown_space: true
      always_send_full_costmap: True

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 8.0
          obstacle_min_range: 0.0
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /map
        map_subscribe_transient_local: True
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 1.0
