<?xml version="1.0"?>
<robot name="ttbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="is_ignition" default="true"/>

  <xacro:include filename="$(find ttbot_description)/urdf/ttbot_gazebo.xacro" />

  <xacro:property name="wheel_radius" value="0.15"/>       
  <xacro:property name="wheel_width"  value="0.06"/>        
  <xacro:property name="wheelbase"    value="0.65"/>         
  <xacro:property name="track_width"  value="0.55"/>        
  <xacro:property name="chassis_length" value="1.0"/>       
  <xacro:property name="chassis_width"  value="0.6"/>      
  <xacro:property name="chassis_height" value="0.45"/>     

  <xacro:macro name="inertial_cyl" params="mass r l">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${(1.0/2.0)*mass*r*r}"
               iyy="${(1.0/12.0)*mass*(3*r*r + l*l)}"
               izz="${(1.0/12.0)*mass*(3*r*r + l*l)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + 0.5 * chassis_height}" rpy="0 0 0"/>
      <material name="red"><color rgba="0.8 0.1 0.1 1.0"/></material>
    </visual>

    <visual>
      <origin xyz="0 0 ${wheel_radius + chassis_height}" rpy="0 0 0"/>
      <geometry><box size="0.8 0.5 0.2"/></geometry>
      <material name="darkred"><color rgba="0.8 0.1 0.1 1.0"/></material>
    </visual>

    <visual>
      <origin xyz="0.4 ${0.5*chassis_width + 0.05} ${wheel_radius + chassis_height}"/>
      <geometry><box size="0.05 0.1 0.05"/></geometry>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <visual>
      <origin xyz="0.4 ${-0.5*chassis_width - 0.05} ${wheel_radius + chassis_height}"/>
      <geometry><box size="0.05 0.1 0.05"/></geometry>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>

    <visual>
      <origin xyz="${0.5*chassis_length + 0.03} ${0.25*chassis_width} ${wheel_radius + 0.6*chassis_height}"/>
      <geometry><sphere radius="0.05"/></geometry>
      <material name="white"><color rgba="1 1 1 1"/></material>
    </visual>
    <visual>
      <origin xyz="${0.5*chassis_length + 0.03} ${-0.25*chassis_width} ${wheel_radius + 0.6*chassis_height}"/>
      <geometry><sphere radius="0.05"/></geometry>
      <material name="white"><color rgba="1 1 1 1"/></material>
    </visual>

    <collision>
      <origin xyz="0 0 ${wheel_radius + 0.5 * chassis_height}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${wheel_radius + 0.5 * chassis_height}" rpy="0 0 0"/>
      <mass value="15.0"/>
      <inertia
        ixx="${(1.0/12.0)*15.0*(chassis_width*chassis_width + chassis_height*chassis_height)}"
        iyy="${(1.0/12.0)*15.0*(chassis_length*chassis_length + chassis_height*chassis_height)}"
        izz="${(1.0/12.0)*15.0*(chassis_length*chassis_length + chassis_width*chassis_width)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <xacro:macro name="wheel_link" params="name">
    <link name="${name}">
      <visual>
        <origin rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1.0"/></material>
      </visual>
      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <xacro:inertial_cyl mass="1.0" r="${wheel_radius}" l="${wheel_width}"/>
    </link>
  </xacro:macro>

  <link name="front_left_steering_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="1e-6" iyy="1e-6" izz="1e-6"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="front_right_steering_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="1e-6" iyy="1e-6" izz="1e-6"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>


  <xacro:wheel_link name="front_left_wheel"/>
  <xacro:wheel_link name="front_right_wheel"/>
  <xacro:wheel_link name="rear_left_wheel"/>
  <xacro:wheel_link name="rear_right_wheel"/>

  <!-- ================= JOINTS ================= -->

  <joint name="front_left_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_steering_link"/>
    <origin xyz="${0.5*wheelbase} ${0.5*track_width} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5236" upper="0.5236" effort="20" velocity="1.0"/>
  </joint>

  <joint name="front_right_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_steering_link"/>
    <origin xyz="${0.5*wheelbase} ${-0.5*track_width} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5236" upper="0.5236" effort="20" velocity="1.0"/>
    <mimic joint="front_left_steering_joint" multiplier="1.0"/>
  </joint>

  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_left_steering_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_right_steering_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="${-0.5*wheelbase} ${0.5*track_width} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="${-0.5*wheelbase} ${-0.5*track_width} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>


  <!-- ================= IMU LINK ================= -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="imu_gray">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.06"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="1e-6" iyy="1e-6" izz="1e-6"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <!-- ================= LIDAR LINK ================= -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
      <material name="lidar_blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- ================= LIDAR JOINT ================= -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${wheel_radius + chassis_height + 0.2}" rpy="0 0 0"/>
  </joint>


  <!-- ================= IMU JOINT ================= -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${wheel_radius + chassis_height + 0.13}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>



  <!-- ================= GPS LINK ================= -->
  <link name="gps_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="gps_black">
        <color rgba="0 0 0 1"/> 
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.06"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="1e-6" iyy="1e-6" izz="1e-6"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- ================= GPS JOINT ================= -->
  <joint name="gps_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="0.1 0 ${wheel_radius + chassis_height + 0.13}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>




  <!-- ================= ROS2_CONTROL ================= -->

  <ros2_control name="ttbot_system" type="system">
    <hardware>
      <xacro:if value="$(arg is_ignition)">
        <plugin>ign_ros2_control/IgnitionSystem</plugin>
      </xacro:if>
      <xacro:unless value="$(arg is_ignition)">
        <plugin>gz_ros2_control/GazeboSystem</plugin>
      </xacro:unless>
    </hardware>

    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="front_left_steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="front_right_steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
  <xacro:ttbot_gazebo/>

</robot>
