/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 640
      height: 480
      scale: 1.0
      # Tính toán từ FOV 1.5184 rad
      fx: 337.2
      fy: 337.2
      cx: 320.0
      cy: 240.0
      # Camera mô phỏng trong Gazebo không bị méo hình
      d0: 0.0
      d1: 0.0
      d2: 0.0
      d3: 0.0